# Generated by Django 4.0.6 on 2022-07-19 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=150)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=150)),
                ('zipcode', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('has_garden', models.BooleanField()),
                ('has_garage', models.BooleanField()),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('sqft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('list_date', models.DateField(auto_now=True)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtors')),
            ],
        ),
    ]
